### ISSUE TITLE
retry intermittent CI fails

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-network-performance#279]
**Description of the Feature to be Added**

Known issue that intermittent CI fails are experienced on runners. The idea is to implement an automatic retry on steps prone to java fails.

**(OPTIONAL) Suggested Implementations**

**Additional context**

As suggested here - [SO thread](https://stackoverflow.com/questions/71574593/how-to-automatically-retry-github-action-jobs-on-failure)

```
uses: nick-fields/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  command: |
    git clone https://github.com/{owner}/{repo}.git
    cd {repo}

```
